name: Typescript Compatible CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install && npm install codecov
    - run: npm run build --if-present
    - run: ./scripts/test.sh
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
